status-im/open-bounty

resources/templates/home.html

Include commit sha in app.js URL to avoid stale caches

---

resources/templates/home.html
src/clj/commiteth/github/core.clj

css cache busting & allow forks

---

src/clj/commiteth/eth/core.clj

feat(eth): Estimate gas instead of hard coding.

---

src/clj/commiteth/eth/core.clj
src/clj/commiteth/eth/multisig_wallet.clj
src/cljs/commiteth/handlers.cljs

Fixes confirmation hash read

---

src/clj/commiteth/eth/core.clj

hardcode gas value at 524288 gas

---

contracts/MultiSigStub.sol
contracts/MultiSigTokenWallet.sol
src/clj/commiteth/eth/multisig_wallet.clj

add function headers to be used in correct ABI recognition.

Web3js abifix

---

resources/sql/queries.sql
src/clj/commiteth/eth/multisig_wallet.clj
src/clj/commiteth/scheduler.clj
src/cljs/commiteth/handlers.cljs
src/cljs/commiteth/manage_payouts.cljs

Submitting my latest changes to develop branch with a PR because of missing write access.

Payout fixes

---

project.clj

add pre compilation of java files in order to make lein run work without cp dancing

---

doc/testing.md

removed Commiteth, added some missing steps and button titles

Updated instructions

---

doc/testing.md

fixed typos, changed commiteth to Open Bounty in more places, added section on how to remove bounty (close issue in GH)

Renaming commiteth and adding info on how to remove bounty

---

resources/public/dest/css/main.css
resources/templates/index.html
static_langing_page/dest/css/main.css
static_langing_page/index.html
static_langing_page/package-lock.json
static_langing_page/src/scss/actions.scss
static_langing_page/src/scss/email-form.scss

Improved landing page. Do not block renderig due to hubspot

---

contracts/DelegatedCall.sol
contracts/ERC20.sol
contracts/MultiSigFactory.sol
contracts/MultiSigStub.sol
contracts/MultiSigTokenWallet.sol
contracts/MultiSigTokenWalletV1.sol
contracts/MultiSigWallet.sol

- Improves readability  of code by heritance
- Removes need of watch function
- Automatically transfer all tokens from a list set in the call
- Never throw when sending tokens
There is two changes needed in SOB codebase:
And need of deploy Library at address 0xcaffe810d0df52e27dc580ad4a3c6283b0094291 in Ropsten and Mainnet, and Factory is at [0x039D2EA34432b7c2691AF4936B502e34A54a79e2](https://ropsten.etherscan.io/address/0x039d2ea34432b7c2691af4936b502e34a54a79e2#code)

Improved Multisig

---

src/clj/commiteth/eth/multisig_wallet.clj

fix abi mismatch

---

src/clj/commiteth/eth/multisig_wallet.clj

Reverts status-im/commiteth#163

Revert "fix abi mismatch"

---

contracts/DelegatedCall.sol
contracts/MultiSigTokenWalletV1.sol
contracts/TokenReg.sol

Reverts status-im/commiteth#162

Revert "fix warnings in contracts"

---

resources/templates/index.html
resources/templates/welcome.html
static_langing_page/index.html
static_langing_page/welcome.html

1. Add Facebook tracking code to home page (it was already on the welcome page)
2. Add HubSpot tracking code to welcome page (it was already on the home page)

Add Facebook and HubSpot tracking codes

---

src/cljs/commiteth/bounties.cljs
src/cljs/commiteth/common.cljs

Also decrease default page size to 15.

Correct 'Showing' label text

---

test/end-to-end/pages/thirdparty/github.py
test/end-to-end/tests/basetestcase.py
test/end-to-end/tests/conftest.py
test/end-to-end/tests/test_contracts.py

added local env, fixed bounty reference

added local env

---

.gitignore
doc/testing.md
test/end-to-end/pages/openbounty/bounties.py
test/end-to-end/pages/openbounty/landing.py
test/end-to-end/pages/thirdparty/github.py
test/end-to-end/pytest.ini
test/end-to-end/tests/__init__.py
test/end-to-end/tests/basetestcase.py
test/end-to-end/tests/config_example.ini
test/end-to-end/tests/test_contracts.py

Adresses to #230 (just rename branch according to guidelines)
In this PR:
* add config support and config_example.ini
* added additional check to bounties_page
* make issue title reusable
* cleaned up code a bit (added comments, changed some absolute values to values from config)
* Change channel and repo path in testing.md
* add cleanup option as variable (not brilliant decision)

Config support and other little improvements

---

src/cljs/commiteth/activity.cljs
src/cljs/commiteth/bounties.cljs
src/cljs/commiteth/common.cljs
src/cljs/commiteth/db.cljs
src/cljs/commiteth/handlers.cljs
src/cljs/commiteth/subscriptions.cljs
src/less/style.less

This will add cursor pointer when hovering over page navigation buttons. Also, now view will scroll upward when navigating to a different page.
Status: Finished.

[FIX #226] Pagination: add cursor pointer for buttons, scroll to top

---

README.md
doc/cookbook.md
doc/testing.md

This includes updates to README.md and a Cookbook for common issue troubleshooting.
Everyone's encouraged to contribute either here or in separate PRs.
**Status**: WIP.

[FIX #198] Docs: more details about configuration and troubleshooting

---

doc/testing.md
test/Jenkinsfile

Addresses to https://github.com/status-im/ideas/issues/40 (MVP v2, create Readme with full setup/configuring instruction)
Also added Jenkinsfile for  sob-end-to-end-tests job

Add end-to-end setup doc and JenkinsFile

---

resources/sql/queries.sql
src/clj/commiteth/routes/services.clj
src/cljs/commiteth/bounties.cljs
src/cljs/commiteth/handlers.cljs
src/cljs/commiteth/subscriptions.cljs
src/cljs/commiteth/ui_model.cljs
src/less/style.less

Sorting and filtering fixes

---

.dockerignore
Dockerfile
Jenkinsfile

jenkinsfile v1

---

.gitignore
README.md
env/dev/resources/config.edn
project.clj
src/clj/commiteth/eth/multisig_wallet.clj

Fixes: #214 
Status: finished.
Notes:
I used the same strategy that uses Luminus for now: http://www.luminusweb.net/docs#anatomy_of_a_luminus_application
And I also made a couple of extra things:
* Add `:user-whitelist` to the base dev config file, which was missing.
* Gitignore `/src/java`.

Unversioned config files

---

src/cljs/commiteth/common.cljs
src/cljs/commiteth/handlers.cljs
src/cljs/commiteth/update_address.cljs

Reverts status-im/open-bounty#240

Revert "[FIX #187] Fix address dropdown in My Payment Details"

---

test/end-to-end/pages/base_page.py
test/end-to-end/pages/thirdparty/github.py
test/end-to-end/requirements.txt
test/end-to-end/tests/__init__.py
test/end-to-end/tests/basetestcase.py
test/end-to-end/tests/config_example.ini
test/end-to-end/tests/postconditions.py
test/end-to-end/tests/test_contracts.py

Addresses to status-im/ideas#40 (MVP v2, automate fork repo)
Add 2 drivers and all pre and postconditions to class_method

BaseTestCase refactoring

---

src/less/style.less

Sorting and filtering fixes 2

---

src/cljs/commiteth/bounties.cljs
src/cljs/commiteth/core.cljs
src/cljs/commiteth/util.cljs
src/less/style.less

Sort and filter fixes 3

---

project.clj
src/clj/commiteth/core.clj

Fixes: #255 
Status: finished.

Remove Cider

---

README.md

Also removed some duplication that seemed uneccessary.

improve postgres setup instructions in readme

---

src/cljs/commiteth/ui_model.cljs

Currency filter should use OR

---

src/less/style.less

Fix vertical height in filter boxes

---

src/cljs/commiteth/common.cljs
src/cljs/commiteth/handlers.cljs
src/cljs/commiteth/update_address.cljs

Reverts status-im/open-bounty#266

Revert "Revert "[FIX #187] Fix address dropdown in My Payment Details""

---

src/cljs/commiteth/ui_model.cljs

Fixes #275 
Status: Finished.
Related: #279

Fix filter currency eth

---

src/cljs/commiteth/bounties.cljs
src/less/style.less

Fixes #262 
Fix filtering and sorting issues:
* exhaustive vertical and horizontal scrolls in dropdowns
* sorting icon size
The issue with scrolls is partially reproducible on macOS High Sierra, on devices with no Retina display (e.g. MacBook Air).

[FIX #262] fix UI filtering/sorting issues (Windows)

---

doc/README.md
doc/testing.md

because of https://github.com/status-im/open-bounty/issues/333

Exclude Mist and Parity from docs

---

test/Dockerfile
test/end-to-end/tests/__init__.py

Added Dockerfile and fixed path to config file

Dockerfile for openbounty tests

---

src/clj/commiteth/routes/webhooks.clj

Iterate through return value of extract-issue-number instead of always picking first

---

test/end-to-end/tests/basetestcase.py

[Automated builds](https://jenkins.status.im/job/end-to-end-tests/job/sob-end-to-end-tests/31/console) are failed because report is not found.

Attempt to fix sob end-to-end test builds

---

doc/decisions/README.md

I came across this while browsing around prior decisions. Love the concept, just updating a link in the readme 👍.

fix DR-0001 link

---

test/end-to-end/pages/base_element.py
test/end-to-end/pages/base_page.py
test/end-to-end/pages/openbounty/activity.py
test/end-to-end/pages/openbounty/bounties.py
test/end-to-end/pages/openbounty/landing.py
test/end-to-end/pages/thirdparty/github.py
test/end-to-end/pages/thirdparty/metamask_plugin.py
test/end-to-end/tests/__init__.py
test/end-to-end/tests/basetestcase.py
test/end-to-end/tests/postconditions.py
test/end-to-end/tests/test_contracts.py

In this PR:
- enable MetaMask installation for BCreator
- full test for claiming bounty (create and edit PR in git and GitHub, check status and claim amount in bounty on "Open Bounties" and "Activity" pages)

Test for bounty claiming

---

resources/migrations/20180403131200-multiple-claims-in-pr.down.sql
resources/migrations/20180403131200-multiple-claims-in-pr.up.sql
resources/sql/queries.sql
src/clj/commiteth/routes/webhooks.clj

Process multiple claims in one PR

---

doc/decisions/0004-use-tachyons.md
src/clj/commiteth/bounties.clj
src/clj/commiteth/routes/services.clj
src/clj/commiteth/routes/webhooks.clj
src/clj/commiteth/scheduler.clj
src/cljc/commiteth/model/bounty.cljc
src/cljc/commiteth/ui/balances.cljc
src/cljc/commiteth/util.cljc
src/cljs/commiteth/activity.cljs
src/cljs/commiteth/bounties.cljs
src/cljs/commiteth/core.cljs
src/cljs/commiteth/handlers.cljs
src/cljs/commiteth/manage_payouts.cljs
src/cljs/commiteth/routes.cljs
src/cljs/commiteth/subscriptions.cljs
src/less/style.less
src/less/tachyons-utils.css

Improved Bounty Issuer Dashboard

---

src/cljs/commiteth/subscriptions.cljs

making a new PR here to trigger jenkins build now that jacob has updated the privileges

log level change for eth gas station
