status-im/open-bounty

- project.clj
- resources/migrations/20170322212119-do-not-store-oauth-token-in-db.up.sql
- resources/sql/queries.sql
- resources/templates/home.html
- src/clj/commiteth/db/users.clj
- src/clj/commiteth/github/core.clj
- src/clj/commiteth/layout.clj
- src/clj/commiteth/routes/home.clj
- src/clj/commiteth/routes/redirect.clj
- src/clj/commiteth/routes/services.clj
- src/cljs/commiteth/core.cljs
- src/cljs/commiteth/db.cljs
- src/cljs/commiteth/handlers.cljs
- src/cljs/commiteth/repos.cljs
- src/cljs/commiteth/subscriptions.cljs
* require only user:email oauth scope when signing up
* if user wants to set bounties on repos, request additional oauth
scopes
* do not store github access tokens on server side and use client-side
localStorage instead
Fixes: #35
Fixes: #40
> Progressive Github permissioning & client-side oauth tokens

- src/cljs/commiteth/core.cljs
- src/less/style.less
Fixes the dropdown menu by moving the background color of the header into a separate div with position absolute. This allows us to have the page overlap with the header background while still being able to set a higher z-index for the header itself preventing the dropdown from being hidden by the page.
> [bug] fix dropdown menu

- src/cljs/commiteth/core.cljs
- src/cljs/commiteth/handlers.cljs
- src/cljs/commiteth/subscriptions.cljs
Start an event listener for mouse-click when opening the dropdown menu and stop it when click event is detected to close it.
> [bug] close dropdown when clicking outside of it

- contracts/DelegatedCall.sol
- contracts/MultiSigTokenWalletV1.sol
- contracts/TokenReg.sol
```text
ricardo@ricardo:~/workspace/commiteth$ truffle compile
Compiling ./contracts/DelegatedCall.sol...
Compiling ./contracts/ERC20.sol...
Compiling ./contracts/MultiSigTokenWalletV1.sol...
Compiling ./contracts/MultiSigWallet.sol...
Compiling ./contracts/TokenReg.sol...
Compilation warnings encountered:
/home/ricardo/workspace/commiteth/contracts/DelegatedCall.sol:64:24: Warning: The "returndatasize" instruction is only available after the Metropolis hard fork. Before that it acts as an invalid instruction.
outSize := returndatasize
^------------^
,/home/ricardo/workspace/commiteth/contracts/DelegatedCall.sol:69:13: Warning: The "returndatacopy" instruction is only available after the Metropolis hard fork. Before that it acts as an invalid instruction.
returndatacopy(outDataPtr, 0, …
```
> fix warnings in contracts

- env/dev/clj/user.clj
- project.clj
Dynamic require of `commiteth.core` allows us to skip autoloading of Java classes during running of lein tasks using `:dev` profile, as described in associated [issue](https://github.com/status-im/open-bounty/issues/206).
Also it seems that `:precomp` profile is not necessary anymore, as its sole purpose seems to  run `build-contracts` without auto-invoking `user.clj` compilation (as its `:source-paths` do not include `env/dev/clj/user.clj`).
> [FIX #206] Dynamically require commiteth.core in user namespace

- env/dev/resources/logback.xml
Log to file only (info and debug levels). Allows working in REPL without getting log spam.
> Suppress stdout logging in dev

- project.clj
Additional source paths help to resolve the Piggieback REPL issue. I was
getting annoying "No such namespace" warnings for commiteth.* namespaces.
I am using vim-fireplace. Detailed flow to reproduce below:
1. Run `lein repl`.
2. In the repl, run `(use 'figwheel-sidecar.repl-api)`, `(start-figwheel!)`, `(start)`.
3. Inside Vim, run `:Piggieback (figwheel-sidecar.repl-api/repl-env)`
Now evaluate e.g. namespace declaration in `commiteth.common` namespace. Result:
```
clojure.lang.ExceptionInfo: No such namespace: commiteth.common, could not locate commiteth/common.cljs, commiteth/common.cljc, or JavaScript source providing "commiteth.common" in file <cljs repl> {:tag
:cljs/analysis-error}
at clojure.core$ex_info.invokeStatic(core.clj:4617)
at clojure.core$ex_info.invoke(core.clj:4617)
at …
```
> Dev fix: add cljs source paths to :dev profile and remove CIDER dep

- README.md
**Summary**: without `wkhtmltoimage` installed and available in PATH, scheduler thread responsible for updating GitHub comments after contract deployment will throw exceptions.
> [FIX #233] Include wkhtmltopdf reference

- src/cljs/commiteth/common.cljs
- src/cljs/commiteth/handlers.cljs
- src/cljs/commiteth/update_address.cljs
**Summary**
Following changes are included:
1. Do not preselect a Metamask address if it has not been set earlier by the user.
2. When Metamask is enabled, add a dummy 'Select address' option to the dropdown when no previous addresses were set.
3. Fix user address setting in 'My Payment Details`. Addresses were correctly stored in the DB, but not in re-frame's app-db.
**Status**: Finished.
> [FIX #187] Fix address dropdown in My Payment Details

- project.clj
- src/cljs/commiteth/activity.cljs
- src/cljs/commiteth/bounties.cljs
- src/cljs/commiteth/common.cljs
- src/cljs/commiteth/manage_payouts.cljs
and replace with goog.date.relative.
Fixes #278 
One aspect of this that I was unable to discern locally was what type the [time] parameter was previously? I assumed milliseconds, but am happy to add additional logic to the extent that it is stored in a different format.
> remove moment.js dependency

- src/cljs/commiteth/core.cljs
- src/less/style.less
This commit fixes the footer gap on the bottom. 
Description: 
Semantic UI CSS defines a padding of 1em to the top and bottom of the segment element. Moving the footer outside the dev.ui.vertical.segment would avoid this gap in the bottom. Also, div.commiteth-footer has excessive margin on top (20px) changed this to 10px to maintain the flow of components (optional).
I also see the fix via margin adjustment (#270), this would not solve the issue as seen in the Manage payouts component. Also, it's not advisable to hard code margin based on the height of footer.
Fixes #268
> Footer is not pinned to the bottom fix

- src/cljs/commiteth/activity.cljs
- src/cljs/commiteth/bounties.cljs
- src/cljs/commiteth/common.cljs
- src/cljs/commiteth/manage_payouts.cljs
Fix for a problem reported by @churik where relative dates were not shown.
This happens with dates older than 2 weeks. I changed the code so that a human-friendly date is displayed instead of a relative statement.
> fix relative time display for long-ago dates

- src/clj/commiteth/core.clj
Fixes #291
Status: Finished
This fixes the code in main to run migrations. The issue was that the original code was using `:jdbc-database-url` vs `:database-url`. It now works for both migrations and rollbacks. I've also simplified the components started by mount as we only need to start env and not the db.
> [Fix #291] Fix command to run migrations

- src/cljs/commiteth/update_address.cljs
**Problem**: if an UPDATE button is clicked when address string is empty (does not matter if Metamask is enabled or not), Schema will complain about failing `Str` check, and this does not look good from user's perspective.
**Solution**: disable UPDATE button if address string is empty.
> Disable UPDATE button if address string is empty

- env/dev/clj/user.clj
- project.clj
Fixes: #306 
Status: Finished
This adds `clojure.tools.namespace` to be able to reload code. It's a better alternative to `reload-all` as outlined [here](https://github.com/clojure/tools.namespace#reloading-code-motivation) and [here](https://github.com/tolitius/mount#the-importance-of-being-reloadable).
If you run:
- `refresh` will reload all changed namespaces with their latest definition.
- `reset` will stop the current system first, then refresh, and restart the
dependencies.
> [Fix #306] Add support for reloading code

- README.md
- project.clj
**Problem**: `build-contracts` takes some time to complete, and by default it is always invoked during `lein repl` or `lein run`.
**Solution**: invoke it separately. Specify this in the README.
> Do not invoke build-contracts when running lein dev profile

- .adr-dir
- doc/decisions/0001-record-decisions.md
- doc/decisions/0002-sign-commits-with-gpg.md
- doc/decisions/README.md
- doc/decisions/templates/template.md
I've mentioned my appreciation of decision reocrds for documentation purposes
before and so this is a proposal to use them as part of Open Bounty.
The motivation to use decision records is in [`0001-recording-decisions.md`](https://github.com/status-im/open-bounty/blob/8a008c144d31ad88acda350ba2cd922bd92be491/doc/decisions/0001-record-decisions.md)
and a first non-meta decision can be found in [`0002-sign-commits-with-gpg.md`](https://github.com/status-im/open-bounty/blob/doc/gpg-decision/doc/decisions/0002-sign-commits-with-gpg.md).
> Introduce Decision Recording w/ GPG Signing Decision

- resources/templates/home.html
- src/cljs/commiteth/common.cljs
- src/cljs/commiteth/manage_payouts.cljs
- src/cljs/commiteth/subscriptions.cljs
Fixes #301: Basic Dashboard reports.
This PR adds some basic stats to the manage payouts screen:
- I manually made myself owner by changing the `owner` and `user_id` columns in the database. It's very possible that I missed something and my database is now "corrupted". #312 would be nice for this.
- I added a new CSS lib [Tachyons](http://tachyons.io/) which I've worked a lot with in the past and which I think might be a good way to tackle #209 (Refactor CSS Usage). Tachyons can be a bit weird at the beginning but I will annotate the code in this PR to explain how things are done and provide links to some useful tools. I hope we can slowly transition components as needed.
> fix #301: add basic stats to manage payouts screen

- project.clj
- src/cljs/commiteth/core.cljs
- src/cljs/commiteth/handlers.cljs
- src/cljs/commiteth/routes.cljs
We've been using secretary but it hasn't been integrated into the codebase very
well. For instance clicking on "Activity" in the menu would not change the url
to include the `#/activity` bit.
This PR fixes that by replacing Secretary with [bide](https://github.com/funcool/bide).
I hope in the future we can extend our usage of URL routing to support page numbers and
other parameters (e.g. sorting) (see #355). This will make it easier for people to share links to
different views of the application.
> swap secretary with bide, move routing into extra ns

- project.clj
- src/clj/commiteth/eth/core.clj
- src/clj/commiteth/eth/multisig_wallet.clj
- src/clj/commiteth/scheduler.clj
Fixes #353 
This fix does the following:
- Move balances updates to 10-min scheduler threads
- Cache return values of `eth.core/create-web3j` and `eth.core/creds` in an atom, reset these when mounting corresponding state
- Add Tufte macros for profiling, can be removed afterwards
> Reduce payout confirmation wait times

- README.md
- resources/sql/queries.sql
- src/clj/commiteth/db/users.clj
- src/clj/commiteth/routes/home.clj
- src/clj/commiteth/routes/redirect.clj
Sometimes it is desirable to fix/develop a feature that does not require any of GitHub integration. Keeping `ngrok` open in order to login into OpenBounty app can slowdown the network connection needlessly in those cases.
This PR adds support for `:dev-login` key in configuration that should be set to your GitHub user name for this feature to work. Clicking on `LOG IN` will then bypass OAuth and redirect to your `server-address` which should be set to `localhost`.
> Quick dev login bypassing OAuth

- src/clj/commiteth/eth/core.clj
This should protect against short-term gas price fluctuations
> Use max(average,average_calc) when calculating gas price

- src/cljs/commiteth/handlers.cljs
- src/cljs/commiteth/routes.cljs
- src/cljs/commiteth/subscriptions.cljs
- src/cljs/commiteth/ui_model.cljs
fixes #355 
Persist bounty filters to query string using bide query params as described in #355.
This needs additional testing, as I could not get the github integration to work locally yet.
The filter UI works as expected, but without actual bounties in the DB it's hard to tell if it really works.
@martinklepsch do you think you could take a look at this?
> [FIX #355] persist bounty filter to query string

- Dockerfile
Add `less` to Dockerfile. Simplifies debugging when e.g. it is necessary to view app logs inside container.
> Add less to Dockerfile

- src/clj/commiteth/db/repositories.clj
I came across this while tailing the logs in order to create a new issue. I've been mucking with my local postgres so much that it seems this is unlikely to be hit by anyone else who isn't reinstalling the app on their repository for the "first" time. 
2018-04-11 12:51:03,387 [XNIO-1 task-21] ERROR commiteth.routes.webhooks - exception when enabling repo #error {
:cause Parameter Mismatch: :repo_name parameter data not found.
> update-repo-state should call db/update-repo-state, not db/update-repo-name

- src/cljs/commiteth/bounties.cljs
- src/cljs/commiteth/common.cljs
- src/less/style.less
The grey box containing claims info will run to the entire width of the column.
> fix padding for dropdown claims

- src/clj/commiteth/bounties.clj
- src/clj/commiteth/eth/core.clj
- src/clj/commiteth/eth/multisig_wallet.clj
- src/clj/commiteth/eth/token_registry.clj
- src/clj/commiteth/scheduler.clj
This addresses #399 by tracking each Ethereum transaction we're doing and incrementing nonces manually if necessary. Because this was a bit more involved code-wise the following things need to be tested thoroughly:
- deployment of contracts
- bounty payout
As we were not able to reproduce #399 on Staging/Ropsten we should test if this PR still works as before on staging and once it's merged into production we can verify that it actually fixes #399.
> fix #399: track each internal transaction and associated nonce

- src/clj/commiteth/util/crypto_fiat_value.clj
**QA NOTES** This change has no user facing effect. It changes how we fetch
price data for our background jobs. Previously everytime we wanted to know the
USD equivalent of some bounties tokens we made a request to some API.
This caused us to get rate limited as described in #434.
This change modifies our code so that we cache the conversion rate for
5 minutes. If you watch the logs on testing you should see log messages like
```
:SNT: Getting price-data from CoinMarketCap (token-id status)
```
appearing once every 10 minutes or so. You should not see these messages
in quick succession.
> fix #434: dont fetch price-info too often

- resources/sql/queries.sql
Fixes #432 
Loading to few activities can cause claims not being displayed as claims and bounties are loaded via separate XHR requests. This change implements a quick fix around that making old activities show up.
Long term we should move claims into the response of `/api/open-bounties` so that they always are available for bounties shown in the UI.
This is also somewhat related to better API pagination as described in https://github.com/status-im/open-bounty/issues/250
> fix #432 load more activities

- src/clj/commiteth/eth/core.clj
Now that we are using eth gas station, we are subject to some timeouts from their api. The error message from cloudfront was quite long so this PR aims to extract just the root cause (in this case a timeout or other error code) so that we humans can understand this message without losing sight of everything else going on. 
Somewhat related to this is that I bumped the default gas price on prod to 10 instead of 5gwei, which is more in keeping with the averages we've been seeing, so that is the new value that will be used if eth gas station is taking too long to respond. 
I had considered a caching/memoization strategy for eth gas station, but given somewhat limited understanding of the volatility of that market, I thought that might do more harm than good in the end versus our current …
> make working with eth gas station more manageable 

- src/clj/commiteth/eth/core.clj
These logs in particular account for the majority of the error emails we get. Since eth gas station times out as much as it works normally, and we have a sensible default for when this happens, I think it makes sense to lower the log level. 
Hopefully this will help us spot issues other issues that actually matter while `sob` is in maintenance mode :+1:
> update log level for eth gas station api from error to debug

- src/cljs/commiteth/core.cljs
Since the scope of the manage bounties tab has grown with revocations, I think it makes sense to get rid of the check hiding the tab unless there are owner bounties present (which require a winner login set on the issue). 
This is also specifically meant to resolve some issues currently being seen in production so it would be nice to get out the door.
> always show manage bounties tab
